# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:

  # Run the build and test steps.
  build:
    docker:
      - image: previousnext/php:7.1-dev
        environment:
          SIMPLETEST_BASE_URL: http://127.0.0.1
          SIMPLETEST_DB: mysql://root:root@127.0.0.1/local
          BROWSERTEST_OUTPUT_DIRECTORY: /data/build/browser_output

      - image: mariadb
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: local
          MYSQL_USER: drupal
          MYSQL_PASSWORD: drupal

      - image: previousnext/gastonjs:1.0.2

    working_directory: /data
    steps:

      - checkout

      - restore_cache:
          keys:
            - agov-v1-{{ arch }}-{{ checksum "composer.lock" }}
            - agov-v1-{{ arch }}

      - run:
          name: "Install dependencies"
          command: |
            make init
            make mkdirs

      - save_cache:
          key: agov-v1-{{ arch }}-{{ checksum "composer.lock" }}
          paths:
            - /root/.composer

      - run:
          name: Lint
          command: |
            make lint

      - run:
          name: Install
          command: |
            make link-profile install

      - run:
          name: Start Apache
          command: |
            tuner --conf=apache > /etc/apache2/mods-enabled/tuner.conf
            tuner --conf=php > /usr/local/etc/php/conf.d/tuner.ini
            apache2ctl start

      - run:
          name: Test PHPUnit
          command: |
            make test-phpunit

      - run:
          name: Test Simpletest
          command: |
            make test-simpletest

      - store_test_results:
          path: build/logs

      - store_artifacts:
          path: /build/browser_output
          destination: tr1
